apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ricxapp
  name: vulnerability-report-reader
rules:
- apiGroups: ["aquasecurity.github.io"]
  resources: ["vulnerabilityreports"]
  verbs: ["get", "list", "watch"]
