apiVersion: apps/v1
kind: Deployment
metadata:
  name: cve-cwe-capec
  namespace: rapps  # 部署在 'rapps' 命名空間中
spec:
  replicas: 1  # 指定 Pod 副本數量
  selector:
    matchLabels:
      app: cve-cwe-capec
  template:
    metadata:
      labels:
        app: cve-cwe-capec
    spec:
      containers:
      - name: cve-cwe-capec
        image: joehuhu/cve_cwe_capec:v1.0.0  # 指定映像和版本
        ports:
        - containerPort: 8080  # 應用程式在容器內使用 8080port
        env:
        - name: KUBECONFIG
          value: /home/joehu/.kube/config
      volumes: []