apiVersion: apps/v1
kind: Deployment
metadata:
  name: cve-cwe-capec
  namespace: rapps  # 部署在 'rapps' 命名空間中
spec:
  replicas: 1  # 指定 Pod 副本數量
  selector:
    matchLabels:
      app: cve-cwe-capec
  template:
    metadata:
      labels:
        app: cve-cwe-capec
    spec:
      containers:
      - name: cve-cwe-capec
        image: joehuhu/cve_cwe_capec:1.0.1  # 指定映像和版本
        ports:
        - containerPort: 8080  # 應用程式在容器內使用 8080 port
        env:
        - name: KUBECONFIG
          value: /home/joe/.kube/config
      imagePullSecrets:
      - name: myregistrykey #因為是將images push到私有的hub，所以要設置權限
